### ISSUE TITLE
Update Vim version requirements to "9.2 or higher" (or refrain from using 9.2 features)

### ISSUE THREAD

**Issue by silverneko** [girishji/vimsuggest#23]
# Context

My environment is WSL ubuntu, which ships with vim 9.1 
```
% vim --version
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Nov 06 2024 19:04:03)
Included patches: 1-16, 647, 678, 697
```

Installing your plugin makes vim (9.1) complain:
```
% vim plugin/vimsuggest.vim
Error detected while compiling /home/yo/.dotfiles/vim/plugged/vimsuggest/plugin/vimsuggest.vim[11]../home/yo/.dotfiles/vim/plugged/vimsuggest/autoload/vimsuggest/addons/addons.vim[21]../home/yo/.dotfiles/vim/plugged/vimsuggest/autoload/vimsuggest/addons/fuzzy.vim[303]..function vimsuggest#addons#fuzzy#FindComplete[27]..<lambda>19:
line    6:
E117: Unknown function: foreach
Press ENTER or type command to continue

```

My work PC (which ships a newer patched vim 9.2) is fine BTW, your plugin works smoothly!

## What's happening

The `foreach` function is planned to be added in vim 9.2 per https://vimhelp.org/version9.txt.html#version-9.2

Which means your plugin won't work on vim9.*1*.... Not until the new `foreach` function gets solidified into vim mainline release.

Could you either
* Update README and docs to reflect the vim version requirements
* Or refrain from using vim 9.2 features before 9.2 formal release, or add version guards around `foreach` callsites (and other vim 9.2 usages).

**Comment by girishji** [comment]
It is in this patch: https://github.com/vim/vim/commit/e79e2077607e8f829ba823308c91104a795736ba#diff-ea763fdb2cbd2223b87bfc5dcbc65b0d0b7a9e07c7738d3ff1d136b98dce06fc

It should work now.

**Comment by silverneko** [comment]
Ah it's introduced with patch number `9.1.0027`, but the `vim` build ubuntu ships with `Included patches: 1-16, 647, 678, 697`. 

They decided to skip patches 17-646 (why?)

Thanks for the fast reply. I think my confusion just stems from that my work computer (running vim 9.1) can run this plugin fine, but my personal PC (also vim 9.1) cannot. So I sorta thought something must be amiss.
I think you can close this issue as moot. but I still hope this can be documented well, or wrap vim 9.1+ features with version guard.
As I think it's a shame that only people using the most bleeding edge build of vim can use your plugin, and I think this plugin is really very decent, and hope it can reach a wider audience.

**Comment by silverneko** [comment]
Okay after your latest change, the plugin still failed to load with this even more cryptic error:

```
Error detected while processing /home/yo/.dotfiles/vim/plugged/vimsuggest/plugin/vimsuggest.vim[11]../home/yo/.dotfiles/vim/plugged/vimsuggest/autoload/vimsuggest/addons/addons.vim:
line   22:
E1053: Could not import "./exec.vim"
```

I don't think it's worth solving this kind of problems anymore. I'll build my own vim binary.
